In [2]:
# ============================================================
# Correlation + Feature Signal Analysis
# Dataset: train_dropmissing.csv
# Purpose: Understand feature relationship with flood_risk_score
# ============================================================

import pandas as pd
import numpy as np
import os

# ============================================================
# 1. Load best current dataset: drop-missing train
# ============================================================

train_path = "../data/processed/train_dropmissing.csv"

# Backup path if your project folder is one level different
if not os.path.exists(train_path):
    train_path = "../MLOpsedian/data/processed/train_dropmissing.csv"

train = pd.read_csv(train_path)

id_col = "record_id"
target = "flood_risk_score"

print("Train path:", train_path)
print("Train shape:", train.shape)
print("Missing values:", train.isnull().sum().sum())
print("Duplicate IDs:", train[id_col].duplicated().sum())
print("Target valid:", train[target].between(0, 1).all())

print("\nTarget summary:")
print(train[target].describe())


# ============================================================
# 2. Add Alpha Pack engineered features
# ============================================================

def add_alpha_pack_features(df):
    df = df.copy()
    eps = 1e-5
    
    if "distance_to_river_m_clipped" in df.columns:
        distance = df["distance_to_river_m_clipped"]
    else:
        distance = df["distance_to_river_m"].clip(lower=0)
    
    if "rainfall_7d_mm_clipped" in df.columns:
        rainfall_7d = df["rainfall_7d_mm_clipped"]
    else:
        rainfall_7d = df["rainfall_7d_mm"].clip(lower=0)
    
    inundation = df["inundation_area_sqm"].clip(lower=0)
    
    df["GOLDEN_distance_rainfall_ratio"] = (
        np.log1p(distance) - np.log1p(rainfall_7d + eps)
    )
    
    df["distance_to_river_DIV_inundation_area"] = (
        distance / (inundation + eps)
    )
    
    df["distance_to_river_DIV_rainfall_7d"] = (
        distance / (rainfall_7d + eps)
    )
    
    df["rainfall_7d_MULT_inundation_area"] = (
        rainfall_7d * inundation
    )
    
    new_cols = [
        "GOLDEN_distance_rainfall_ratio",
        "distance_to_river_DIV_inundation_area",
        "distance_to_river_DIV_rainfall_7d",
        "rainfall_7d_MULT_inundation_area"
    ]
    
    for col in new_cols:
        df[col] = df[col].replace([np.inf, -np.inf], np.nan)
        df[col] = df[col].fillna(df[col].median())
    
    return df

train_fe = add_alpha_pack_features(train)

print("\nAfter Alpha Pack feature engineering:")
print("Train shape:", train_fe.shape)
print("Missing values:", train_fe.isnull().sum().sum())


# ============================================================
# 3. Target balance check
# ============================================================

target_bins = pd.cut(
    train_fe[target],
    bins=[-0.001, 0.2, 0.4, 0.6, 0.8, 1.001],
    labels=[
        "0.0-0.2 very low",
        "0.2-0.4 low",
        "0.4-0.6 medium",
        "0.6-0.8 high",
        "0.8-1.0 very high"
    ]
)

target_balance = pd.DataFrame({
    "count": target_bins.value_counts().sort_index(),
    "percentage": (target_bins.value_counts(normalize=True).sort_index() * 100).round(2)
})

print("\nTarget balance:")
display(target_balance)


# ============================================================
# 4. Numeric Pearson + Spearman correlation
# ============================================================

exclude_cols = [id_col, target]

numeric_cols = [
    col for col in train_fe.select_dtypes(include=[np.number]).columns
    if col not in exclude_cols
]

correlation_rows = []

for_numeric_note = len(numeric_cols)
print("\nNumber of numeric features checked:", for_numeric_note)

for col in numeric_cols:
    pearson_corr = train_fe[col].corr(train_fe[target], method="pearson")
    spearman_corr = train_fe[col].corr(train_fe[target], method="spearman")
    
    correlation_rows.append({
        "feature": col,
        "pearson_corr": pearson_corr,
        "abs_pearson_corr": abs(pearson_corr),
        "spearman_corr": spearman_corr,
        "abs_spearman_corr": abs(spearman_corr),
        "feature_min": train_fe[col].min(),
        "feature_max": train_fe[col].max(),
        "feature_mean": train_fe[col].mean(),
        "feature_std": train_fe[col].std()
    })

numeric_corr_df = pd.DataFrame(correlation_rows)

numeric_corr_df = numeric_corr_df.sort_values(
    "abs_spearman_corr",
    ascending=False
).reset_index(drop=True)

print("\nTop 25 numeric features by absolute Spearman correlation:")
display(numeric_corr_df.head(25))


# ============================================================
# 5. Alpha engineered feature correlations
# ============================================================

alpha_engineered_features = [
    "GOLDEN_distance_rainfall_ratio",
    "distance_to_river_DIV_inundation_area",
    "distance_to_river_DIV_rainfall_7d",
    "rainfall_7d_MULT_inundation_area"
]

alpha_corr_df = numeric_corr_df[
    numeric_corr_df["feature"].isin(alpha_engineered_features)
].copy()

print("\nAlpha engineered feature correlations:")
display(alpha_corr_df)


# ============================================================
# 6. Categorical target mean analysis
# ============================================================

categorical_cols = [
    col for col in train_fe.select_dtypes(include=["object", "str"]).columns
    if col != id_col
]

categorical_summary_rows = []
category_detail_tables = {}

print("\nNumber of categorical features checked:", len(categorical_cols))
print(categorical_cols)

for col in categorical_cols:
    category_stats = (
        train_fe.groupby(col)[target]
        .agg(["count", "mean", "std", "min", "max"])
        .sort_values("mean", ascending=False)
        .reset_index()
    )
    
    category_stats["feature"] = col
    
    # Save detailed table for this feature
    category_detail_tables[col] = category_stats
    
    if len(category_stats) > 0:
        max_mean = category_stats["mean"].max()
        min_mean = category_stats["mean"].min()
        target_mean_gap = max_mean - min_mean
        
        top_category = category_stats.iloc[0][col]
        bottom_category = category_stats.iloc[-1][col]
        
        categorical_summary_rows.append({
            "feature": col,
            "unique_values": train_fe[col].nunique(dropna=False),
            "max_category_mean": max_mean,
            "min_category_mean": min_mean,
            "target_mean_gap": target_mean_gap,
            "top_category": top_category,
            "bottom_category": bottom_category,
            "largest_category_count": train_fe[col].value_counts(dropna=False).max()
        })

categorical_signal_df = pd.DataFrame(categorical_summary_rows)

categorical_signal_df = categorical_signal_df.sort_values(
    "target_mean_gap",
    ascending=False
).reset_index(drop=True)

print("\nCategorical features ranked by target mean gap:")
display(categorical_signal_df)


# ============================================================
# 7. Show detailed category means for important categorical features
# ============================================================

important_categorical_to_show = [
    "reason_not_good_to_live",
    "is_good_to_live",
    "flood_occurrence_current_event",
    "road_quality",
    "landcover",
    "soil_type",
    "water_presence_flag",
    "district"
]

for col in important_categorical_to_show:
    if col in category_detail_tables:
        print("\n" + "=" * 70)
        print("Category target means:", col)
        display(category_detail_tables[col].head(15))


# ============================================================
# 8. Compare Alpha Pack selected features with all available features
# ============================================================

alpha_pack_features = [
    "district",
    "distance_to_river_DIV_inundation_area",
    "distance_to_river_DIV_rainfall_7d",
    "GOLDEN_distance_rainfall_ratio",
    "generation_date",
    "reason_not_good_to_live",
    "inundation_area_sqm",
    "infrastructure_score",
    "extreme_weather_index",
    "terrain_roughness_index",
    "road_quality",
    "monthly_rainfall_mm_log1p",
    "landcover",
    "rainfall_7d_MULT_inundation_area",
    "place_name",
    "rainfall_7d_mm",
    "seasonal_index",
    "ndwi_qmap",
    "latitude",
    "longitude",
    "distance_to_river_m",
    "ndwi",
    "water_supply",
    "nearest_evac_km_log1p",
    "elevation_m_yeojohnson",
    "monthly_rainfall_mm",
    "socioeconomic_status_index",
    "population_density_per_km2_log1p",
    "water_presence_flag",
    "nearest_hospital_km_log1p",
    "ndvi_qmap",
    "flood_occurrence_current_event",
    "rainfall_7d_mm_log1p",
    "soil_type",
    "population_density_per_km2"
]

numeric_corr_df["in_alpha_pack"] = numeric_corr_df["feature"].isin(alpha_pack_features)

print("\nTop numeric features not in Alpha Pack:")
display(
    numeric_corr_df[
        numeric_corr_df["in_alpha_pack"] == False
    ].head(20)
)

print("\nTop numeric features in Alpha Pack:")
display(
    numeric_corr_df[
        numeric_corr_df["in_alpha_pack"] == True
    ].head(20)
)


# ============================================================
# 9. Suggested correlation-guided candidates
# ============================================================

top_numeric_by_spearman = numeric_corr_df.head(30)["feature"].tolist()
top_categorical_by_gap = categorical_signal_df.head(10)["feature"].tolist()

suggested_feature_candidates = list(dict.fromkeys(
    alpha_pack_features +
    top_numeric_by_spearman +
    top_categorical_by_gap
))

# Remove ID and target if accidentally included
suggested_feature_candidates = [
    col for col in suggested_feature_candidates
    if col not in [id_col, target]
]

suggested_feature_candidates_df = pd.DataFrame({
    "feature": suggested_feature_candidates
})

print("\nSuggested feature candidate count:")
print(len(suggested_feature_candidates))

print("\nSuggested feature candidates:")
display(suggested_feature_candidates_df)


# ============================================================
# 10. Save reports
# ============================================================

os.makedirs("../reports", exist_ok=True)

numeric_corr_df.to_csv(
    "../reports/numeric_correlation_dropmissing.csv",
    index=False
)

alpha_corr_df.to_csv(
    "../reports/alpha_feature_correlation_dropmissing.csv",
    index=False
)

categorical_signal_df.to_csv(
    "../reports/categorical_target_signal_dropmissing.csv",
    index=False
)

target_balance.to_csv(
    "../reports/target_balance_dropmissing.csv"
)

suggested_feature_candidates_df.to_csv(
    "../reports/suggested_feature_candidates_dropmissing.csv",
    index=False
)

# Save detailed category mean reports into one file
all_category_details = []

for col, detail_df in category_detail_tables.items():
    temp = detail_df.copy()
    all_category_details.append(temp)

all_category_details_df = pd.concat(all_category_details, axis=0)

all_category_details_df.to_csv(
    "../reports/category_target_mean_details_dropmissing.csv",
    index=False
)

print("\nFiles saved:")
print("../reports/numeric_correlation_dropmissing.csv")
print("../reports/alpha_feature_correlation_dropmissing.csv")
print("../reports/categorical_target_signal_dropmissing.csv")
print("../reports/target_balance_dropmissing.csv")
print("../reports/suggested_feature_candidates_dropmissing.csv")
print("../reports/category_target_mean_details_dropmissing.csv")

Train path: ../MLOpsedian/data/processed/train_dropmissing.csv
Train shape: (15518, 69)
Missing values: 0
Duplicate IDs: 0
Target valid: True

Target summary:
count    15518.000000
mean         0.478479
std          0.236625
min          0.000000
25%          0.340425
50%          0.474400
75%          0.614575
max          1.000000
Name: flood_risk_score, dtype: float64

After Alpha Pack feature engineering:
Train shape: (15518, 73)
Missing values: 0

Target balance:

                   count  percentage
flood_risk_score
0.0-0.2 very low    1899       12.24
0.2-0.4 low         3455       22.26
0.4-0.6 medium      5993       38.62
0.6-0.8 high        2655       17.11
0.8-1.0 very high   1516        9.77

Number of numeric features checked: 57

Top 25 numeric features by absolute Spearman correlation:

/Users/esanduepa/Library/Python/3.13/lib/python/site-packages/numpy/lib/_function_base_impl.py:3023: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/Users/esanduepa/Library/Python/3.13/lib/python/site-packages/numpy/lib/_function_base_impl.py:3024: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/Users/esanduepa/Library/Python/3.13/lib/python/site-packages/pandas/core/nanops.py:1673: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]

,feature,pearson_corr,abs_pearson_corr,spearman_corr,abs_spearman_corr,feature_min,feature_max,feature_mean,feature_std
0,GOLDEN_distance_rainfall_ratio,0.107032,0.107032,0.127029,0.127029,-6.343150,9.347909e+00,2.967161e+00,1.766725e+00
1,distance_to_river_DIV_rainfall_7d,0.016263,0.016263,0.126500,0.126500,0.000000,8.030600e+08,1.080125e+06,1.901416e+07
2,distance_to_river_DIV_inundation_area,0.093779,0.093779,0.126372,0.126372,0.000000,1.792374e+01,5.380510e-01,9.090127e-01
3,rainfall_7d_MULT_inundation_area,-0.063839,0.063839,-0.115792,0.115792,0.000000,2.465949e+07,7.082797e+05,1.141829e+06
4,inundation_area_sqm,-0.083289,0.083289,-0.107131,0.107131,396.000000,1.044890e+05,7.289640e+03,5.808291e+03
5,distance_to_river_m,0.081599,0.081599,0.095963,0.095963,-485.397750,1.680200e+04,2.007627e+03,2.028008e+03
6,distance_to_river_m_log1p,0.088798,0.088798,0.095963,0.095963,0.693147,9.757849e+00,7.538347e+00,7.626451e-01
7,distance_to_river_m_clipped,0.081466,0.081466,0.095957,0.095957,0.000000,1.680200e+04,2.009220e+03,2.026302e+03
8,rainfall_7d_mm_clipped,-0.061331,0.061331,-0.086800,0.086800,0.000000,8.207505e+02,8.415104e+01,7.832030e+01
9,rainfall_7d_mm,-0.061318,0.061318,-0.086795,0.086795,-49.199358,8.207505e+02,8.402691e+01,7.847845e+01
10,rainfall_7d_mm_log1p,-0.073253,0.073253,-0.086795,0.086795,0.693147,6.770732e+00,4.782910e+00,4.882385e-01
11,extreme_weather_index,-0.057625,0.057625,-0.065519,0.065519,0.132326,1.000000e+00,7.058196e-01,1.132276e-01
12,infrastructure_score,0.043254,0.043254,0.045093,0.045093,5.000000,9.500000e+01,4.625951e+01,1.993080e+01
13,terrain_roughness_index,-0.025747,0.025747,-0.039030,0.039030,0.184688,2.206066e+01,8.159931e-01,3.099950e-01
14,historical_flood_count,-0.032373,0.032373,-0.036582,0.036582,0.000000,5.000000e+00,2.016368e-01,5.084881e-01
15,monthly_rainfall_mm_clipped,-0.025738,0.025738,-0.036083,0.036083,0.000000,2.032274e+03,2.240928e+02,1.810966e+02
16,monthly_rainfall_mm,-0.025775,0.025775,-0.036077,0.036077,-79.170571,2.032274e+03,2.238754e+02,1.813985e+02
17,monthly_rainfall_mm_log1p,-0.028491,0.028491,-0.036077,0.036077,0.693147,7.656074e+00,5.572304e+00,5.584915e-01
18,ndwi_clipped,-0.024691,0.024691,-0.031924,0.031924,-1.000000,1.000000e+00,3.689638e-02,2.725037e-01
19,ndwi,-0.023743,0.023743,-0.031924,0.031924,-1.000000,1.596308e+00,3.829192e-02,2.783852e-01
20,ndwi_qmap,-0.024446,0.024446,-0.031924,0.031924,-5.199338,5.199338e+00,-7.096927e-06,1.013873e+00
21,population_density_per_km2,-0.020962,0.020962,-0.030482,0.030482,10.000000,6.642296e+03,6.602561e+02,6.553855e+02
22,population_density_per_km2_log1p,-0.024878,0.024878,-0.030482,0.030482,2.397895,8.801364e+00,5.994384e+00,1.239018e+00
23,built_up_percent_qmap,-0.013372,0.013372,-0.018971,0.018971,-5.199338,5.199338e+00,-4.327118e-01,1.952642e+00
24,built_up_percent,-0.017550,0.017550,-0.018971,0.018971,1.000000,1.774979e+02,2.566639e+01,1.998937e+01

Alpha engineered feature correlations:

,feature,pearson_corr,abs_pearson_corr,spearman_corr,abs_spearman_corr,feature_min,feature_max,feature_mean,feature_std
0,GOLDEN_distance_rainfall_ratio,0.107032,0.107032,0.127029,0.127029,-6.34315,9.347909e+00,2.967161e+00,1.766725e+00
1,distance_to_river_DIV_rainfall_7d,0.016263,0.016263,0.126500,0.126500,0.00000,8.030600e+08,1.080125e+06,1.901416e+07
2,distance_to_river_DIV_inundation_area,0.093779,0.093779,0.126372,0.126372,0.00000,1.792374e+01,5.380510e-01,9.090127e-01
3,rainfall_7d_MULT_inundation_area,-0.063839,0.063839,-0.115792,0.115792,0.00000,2.465949e+07,7.082797e+05,1.141829e+06

Number of categorical features checked: 14
['district', 'place_name', 'landcover', 'soil_type', 'water_supply', 'electricity', 'road_quality', 'urban_rural', 'water_presence_flag', 'flood_occurrence_current_event', 'is_good_to_live', 'reason_not_good_to_live', 'is_synthetic', 'generation_date']

Categorical features ranked by target mean gap:

,feature,unique_values,max_category_mean,min_category_mean,target_mean_gap,top_category,bottom_category,largest_category_count
0,place_name,792,0.672823,0.304317,0.368506,Nayagama West,Polanuwara,34
1,generation_date,730,0.650645,0.296460,0.354185,2025-07-29,2024-03-31,40
2,district,26,0.540287,0.408144,0.132143,Vavuniya,Colombo,673
3,water_presence_flag,3,0.563111,0.466256,0.096855,Missing,Likely,9095
4,reason_not_good_to_live,9,0.522539,0.429762,0.092777,Poor infrastructure; No road access,High flood risk,10088
5,landcover,8,0.521576,0.468297,0.053279,Missing,Wetland,4176
6,flood_occurrence_current_event,2,0.497747,0.461400,0.036347,No,Yes,8226
7,is_good_to_live,2,0.509265,0.475799,0.033466,Yes,No,14275
8,road_quality,5,0.501402,0.468031,0.033371,Missing,Fair,6921
9,soil_type,6,0.503900,0.472611,0.031289,Missing,Loamy,3188
10,water_supply,6,0.489122,0.460831,0.028291,Tube-well,Missing,5355
11,is_synthetic,2,0.501493,0.478380,0.023114,Missing,True,15451
12,electricity,4,0.483463,0.463230,0.020233,Off-grid (solar),Mixed,11407
13,urban_rural,3,0.489264,0.477694,0.011570,Missing,Urban,10471

======================================================================
Category target means: reason_not_good_to_live

,reason_not_good_to_live,count,mean,std,min,max,feature
0,Poor infrastructure; No road access,99,0.522539,0.232118,0.0,1.0,reason_not_good_to_live
1,Missing,641,0.505143,0.249073,0.0,1.0,reason_not_good_to_live
2,No road access,66,0.498589,0.213839,0.0,1.0,reason_not_good_to_live
3,Poor infrastructure,1923,0.487353,0.230368,0.0,1.0,reason_not_good_to_live
4,Other,10088,0.487005,0.235734,0.0,1.0,reason_not_good_to_live
5,High flood risk; Poor infrastructure; No road ...,127,0.439824,0.253842,0.0,1.0,reason_not_good_to_live
6,High flood risk; No road access,59,0.435649,0.236359,0.0,1.0,reason_not_good_to_live
7,High flood risk; Poor infrastructure,1452,0.432595,0.236963,0.0,1.0,reason_not_good_to_live
8,High flood risk,1063,0.429762,0.233798,0.0,1.0,reason_not_good_to_live

======================================================================
Category target means: is_good_to_live

  is_good_to_live  count      mean       std  min  max          feature
0             Yes   1243  0.509265  0.244033  0.0  1.0  is_good_to_live
1              No  14275  0.475799  0.235787  0.0  1.0  is_good_to_live

======================================================================
Category target means: flood_occurrence_current_event

,flood_occurrence_current_event,count,mean,std,min,max,feature
0,No,7292,0.497747,0.237857,0.0,1.0,flood_occurrence_current_event
1,Yes,8226,0.461400,0.234220,0.0,1.0,flood_occurrence_current_event

======================================================================
Category target means: road_quality

     road_quality  count      mean       std  min  max       feature
0         Missing     87  0.501402  0.244527  0.0  1.0  road_quality
1    Good (paved)   6921  0.490177  0.237788  0.0  1.0  road_quality
2  No road access    782  0.470031  0.228100  0.0  1.0  road_quality
3  Poor (unpaved)   3104  0.469447  0.240125  0.0  1.0  road_quality
4            Fair   4624  0.468031  0.233026  0.0  1.0  road_quality

======================================================================
Category target means: landcover

     landcover  count      mean       std  min  max    feature
0      Missing     55  0.521576  0.249573  0.0  1.0  landcover
1        Urban   2886  0.487275  0.239000  0.0  1.0  landcover
2       Forest   2345  0.481069  0.235375  0.0  1.0  landcover
3  Agriculture   4176  0.478432  0.236814  0.0  1.0  landcover
4        Scrub   1860  0.478160  0.233704  0.0  1.0  landcover
5   Plantation   1928  0.472751  0.235644  0.0  1.0  landcover
6    Bare Soil    743  0.469774  0.235548  0.0  1.0  landcover
7      Wetland   1525  0.468297  0.238013  0.0  1.0  landcover

======================================================================
Category target means: soil_type

  soil_type  count      mean       std  min  max    feature
0   Missing     60  0.503900  0.236178  0.0  1.0  soil_type
1      Clay   3089  0.487248  0.237792  0.0  1.0  soil_type
2     Sandy   3085  0.480826  0.232883  0.0  1.0  soil_type
3     Peaty   3066  0.476979  0.237295  0.0  1.0  soil_type
4     Silty   3188  0.474255  0.234332  0.0  1.0  soil_type
5     Loamy   3030  0.472611  0.240778  0.0  1.0  soil_type

======================================================================
Category target means: water_presence_flag

,water_presence_flag,count,mean,std,min,max,feature
0,Missing,64,0.563111,0.236691,0.0372,1.0,water_presence_flag
1,Unlikely,9095,0.486430,0.235645,0.0000,1.0,water_presence_flag
2,Likely,6359,0.466256,0.237399,0.0000,1.0,water_presence_flag

======================================================================
Category target means: district

        district  count      mean       std  min  max   feature
0       Vavuniya    627  0.540287  0.222696  0.0  1.0  district
1     Monaragala    592  0.536042  0.228344  0.0  1.0  district
2     Mullaitivu    623  0.518111  0.240919  0.0  1.0  district
3        Badulla    635  0.516471  0.220362  0.0  1.0  district
4        Missing     61  0.510641  0.245176  0.0  1.0  district
5     Kurunegala    623  0.505595  0.245876  0.0  1.0  district
6          Kandy    673  0.505492  0.233019  0.0  1.0  district
7         Matara    600  0.501420  0.223846  0.0  1.0  district
8       Puttalam    631  0.501418  0.229702  0.0  1.0  district
9        Kegalle    606  0.495485  0.225955  0.0  1.0  district
10      Kalutara    619  0.490285  0.241028  0.0  1.0  district
11       Gampaha    599  0.482907  0.248507  0.0  1.0  district
12    Batticaloa    615  0.482414  0.247018  0.0  1.0  district
13  Anuradhapura    626  0.479833  0.226913  0.0  1.0  district
14        Mannar    634  0.471270  0.228931  0.0  1.0  district

Top numeric features not in Alpha Pack:

,feature,pearson_corr,abs_pearson_corr,spearman_corr,abs_spearman_corr,feature_min,feature_max,feature_mean,feature_std,in_alpha_pack
6,distance_to_river_m_log1p,0.088798,0.088798,0.095963,0.095963,0.693147,9.757849,7.538347,0.762645,False
7,distance_to_river_m_clipped,0.081466,0.081466,0.095957,0.095957,0.000000,16802.000000,2009.220177,2026.301984,False
8,rainfall_7d_mm_clipped,-0.061331,0.061331,-0.086800,0.086800,0.000000,820.750474,84.151041,78.320295,False
14,historical_flood_count,-0.032373,0.032373,-0.036582,0.036582,0.000000,5.000000,0.201637,0.508488,False
15,monthly_rainfall_mm_clipped,-0.025738,0.025738,-0.036083,0.036083,0.000000,2032.274155,224.092813,181.096563,False
18,ndwi_clipped,-0.024691,0.024691,-0.031924,0.031924,-1.000000,1.000000,0.036896,0.272504,False
23,built_up_percent_qmap,-0.013372,0.013372,-0.018971,0.018971,-5.199338,5.199338,-0.432712,1.952642,False
24,built_up_percent,-0.017550,0.017550,-0.018971,0.018971,1.000000,177.497891,25.666388,19.989374,False
25,built_up_percent_clipped,-0.017685,0.017685,-0.018971,0.018971,1.000000,100.000000,25.505903,19.173825,False
26,drainage_index_yeojohnson,-0.017667,0.017667,-0.016338,0.016338,0.002997,1.283534,0.440664,0.184006,False
27,drainage_index,-0.018171,0.018171,-0.016338,0.016338,0.003000,1.779877,0.507423,0.232570,False
28,drainage_index_clipped,-0.017455,0.017455,-0.016334,0.016334,0.003000,1.000000,0.505375,0.225653,False
29,generation_day,-0.014339,0.014339,-0.015489,0.015489,1.000000,31.000000,15.822142,8.793592,False
30,monthly_rainfall_mm_invalid_flag,0.011337,0.011337,0.012489,0.012489,0.000000,1.000000,0.005220,0.072061,False
31,distance_to_river_m_invalid_flag,-0.013786,0.013786,-0.012243,0.012243,0.000000,1.000000,0.006637,0.081202,False
32,rainfall_7d_mm_invalid_flag,0.007935,0.007935,0.010408,0.010408,0.000000,1.000000,0.005220,0.072061,False
35,ndvi_invalid_flag,-0.008367,0.008367,-0.007904,0.007904,0.000000,1.000000,0.004060,0.063589,False
36,drainage_index_invalid_flag,-0.004621,0.004621,-0.006827,0.006827,0.000000,1.000000,0.004060,0.063589,False
37,generation_quarter,-0.007037,0.007037,-0.006131,0.006131,1.000000,4.000000,2.506509,1.115974,False
38,generation_dayofyear,-0.007272,0.007272,-0.006084,0.006084,1.000000,366.000000,183.022812,105.585688,False

Top numeric features in Alpha Pack:

,feature,pearson_corr,abs_pearson_corr,spearman_corr,abs_spearman_corr,feature_min,feature_max,feature_mean,feature_std,in_alpha_pack
0,GOLDEN_distance_rainfall_ratio,0.107032,0.107032,0.127029,0.127029,-6.343150,9.347909e+00,2.967161e+00,1.766725e+00,True
1,distance_to_river_DIV_rainfall_7d,0.016263,0.016263,0.126500,0.126500,0.000000,8.030600e+08,1.080125e+06,1.901416e+07,True
2,distance_to_river_DIV_inundation_area,0.093779,0.093779,0.126372,0.126372,0.000000,1.792374e+01,5.380510e-01,9.090127e-01,True
3,rainfall_7d_MULT_inundation_area,-0.063839,0.063839,-0.115792,0.115792,0.000000,2.465949e+07,7.082797e+05,1.141829e+06,True
4,inundation_area_sqm,-0.083289,0.083289,-0.107131,0.107131,396.000000,1.044890e+05,7.289640e+03,5.808291e+03,True
5,distance_to_river_m,0.081599,0.081599,0.095963,0.095963,-485.397750,1.680200e+04,2.007627e+03,2.028008e+03,True
9,rainfall_7d_mm,-0.061318,0.061318,-0.086795,0.086795,-49.199358,8.207505e+02,8.402691e+01,7.847845e+01,True
10,rainfall_7d_mm_log1p,-0.073253,0.073253,-0.086795,0.086795,0.693147,6.770732e+00,4.782910e+00,4.882385e-01,True
11,extreme_weather_index,-0.057625,0.057625,-0.065519,0.065519,0.132326,1.000000e+00,7.058196e-01,1.132276e-01,True
12,infrastructure_score,0.043254,0.043254,0.045093,0.045093,5.000000,9.500000e+01,4.625951e+01,1.993080e+01,True
13,terrain_roughness_index,-0.025747,0.025747,-0.039030,0.039030,0.184688,2.206066e+01,8.159931e-01,3.099950e-01,True
16,monthly_rainfall_mm,-0.025775,0.025775,-0.036077,0.036077,-79.170571,2.032274e+03,2.238754e+02,1.813985e+02,True
17,monthly_rainfall_mm_log1p,-0.028491,0.028491,-0.036077,0.036077,0.693147,7.656074e+00,5.572304e+00,5.584915e-01,True
19,ndwi,-0.023743,0.023743,-0.031924,0.031924,-1.000000,1.596308e+00,3.829192e-02,2.783852e-01,True
20,ndwi_qmap,-0.024446,0.024446,-0.031924,0.031924,-5.199338,5.199338e+00,-7.096927e-06,1.013873e+00,True
21,population_density_per_km2,-0.020962,0.020962,-0.030482,0.030482,10.000000,6.642296e+03,6.602561e+02,6.553855e+02,True
22,population_density_per_km2_log1p,-0.024878,0.024878,-0.030482,0.030482,2.397895,8.801364e+00,5.994384e+00,1.239018e+00,True
33,longitude,0.012197,0.012197,0.010382,0.010382,79.650121,8.189999e+01,8.076780e+01,6.494543e-01,True
34,socioeconomic_status_index,0.007271,0.007271,0.008655,0.008655,0.185235,8.492507e-01,5.080231e-01,1.172090e-01,True
43,elevation_m_yeojohnson,0.009057,0.009057,0.003894,0.003894,-355.462483,1.442205e+02,2.598486e+01,3.096020e+01,True

Suggested feature candidate count:
49

Suggested feature candidates:

                                  feature
0                                district
1   distance_to_river_DIV_inundation_area
2       distance_to_river_DIV_rainfall_7d
3          GOLDEN_distance_rainfall_ratio
4                         generation_date
5                 reason_not_good_to_live
6                     inundation_area_sqm
7                    infrastructure_score
8                   extreme_weather_index
9                 terrain_roughness_index
10                           road_quality
11              monthly_rainfall_mm_log1p
12                              landcover
13       rainfall_7d_MULT_inundation_area
14                             place_name
15                         rainfall_7d_mm
16                         seasonal_index
17                              ndwi_qmap
18                               latitude
19                              longitude
20                    distance_to_river_m
21                                   ndwi
22                           water_supply
23                  nearest_evac_km_log1p
24                 elevation_m_yeojohnson
25                    monthly_rainfall_mm
26             socioeconomic_status_index
27       population_density_per_km2_log1p
28                    water_presence_flag
29              nearest_hospital_km_log1p
30                              ndvi_qmap
31         flood_occurrence_current_event
32                   rainfall_7d_mm_log1p
33                              soil_type
34             population_density_per_km2
35              distance_to_river_m_log1p
36            distance_to_river_m_clipped
37                 rainfall_7d_mm_clipped
38                 historical_flood_count
39            monthly_rainfall_mm_clipped
40                           ndwi_clipped
41                  built_up_percent_qmap
42                       built_up_percent
43               built_up_percent_clipped
44              drainage_index_yeojohnson
45                         drainage_index
46                 drainage_index_clipped
47                         generation_day
48                        is_good_to_live

Files saved:
../reports/numeric_correlation_dropmissing.csv
../reports/alpha_feature_correlation_dropmissing.csv
../reports/categorical_target_signal_dropmissing.csv
../reports/target_balance_dropmissing.csv
../reports/suggested_feature_candidates_dropmissing.csv
../reports/category_target_mean_details_dropmissing.csv